from multiprocessing import Pool, freeze_support, RLock, current_process
from pathlib import Path
from tqdm import tqdm
from Analysis import Analysis
from CreateDot import todot, find_leak, todot_native
from APKReader import APKReader
import sys
import time
import argparse
import shutil

class Main:
    def __init__(self):
        self.analyses = {}
        self.clean = True

    def set_options(self, analyses, keep_jar):
        self.analyses['all'] = True if 'all' in analyses else False
        self.analyses['dse'] = True if 'dse' in analyses else False
        self.analyses['cha'] = True if 'cha' in analyses else False
        self.analyses['xml'] = True if 'xml' in analyses else False
        self.clean = False if keep_jar is True else True

    def single_process(self, batch, tqdm_index, stamp=None, taintlevel=0):
        """ Iterate through directory for .apk files """
        id = '_' + stamp if stamp is not None else ''
    
        with tqdm(batch, position=tqdm_index) as progress:
            for file in progress:
                progress.set_postfix_str(file.stem)
                start = time.time()
                
                # Preprocessing APK file
                apk_proj_path = APKReader().analyse_file(file, self.clean)
                print('DONE DEX2JAR.')

                # Performing DSE and CHA to generate CFG
                file = Path(apk_proj_path)
                if file.exists():   
                    gen = Analysis()

                    if self.analyses['all'] or self.analyses['xml']:
                        gen.getPermissionsFromXML(str(file.absolute()))
                    if self.analyses['all'] or self.analyses['dse']:
                        gen.startDseByEntryPoints(str(file.absolute()))
                    if self.analyses['all'] or self.analyses['cha']:
                        gen.startChaBySources(str(file.absolute()))
                    
                exe_time = time.time() - start
                print('DONE analyses in', exe_time , '(s)')

                # Analyse output generated by DSE
                print("=== DSE result ===  ")
                self.analyse_output(apk_proj_path)

                # Execution time for each item
                with open(APKReader.RESULT_FOLDER + '/time' + id + '.csv', 'a') as csv_file:
                    line = file.stem + ', ' + str(exe_time) + '\n'
                    csv_file.write(line)

    def __split_chunk(self, full, n):
        (chunk_size, mod_size) = divmod(len(full), n) 
        chunk_sizes = [chunk_size for i in range(n-1)] + [chunk_size+mod_size]
        i = 0
        for k_size in chunk_sizes:
            yield full[i: i + k_size]
            i = i + k_size
    
    def run(self, apk_path, proc_no = 2, stamp=None, exclude=None):
        """ Starting multiple processes for file in apk_path"""
        n_processes = proc_no
        file_list = list(Path(apk_path).rglob('*.apk')) if Path(apk_path).is_dir() else [Path(apk_path)]  

        if len(file_list) > n_processes and n_processes > 1:
            freeze_support()
            file_chunks = self.__split_chunk(file_list, n_processes)
            pool = Pool(n_processes, initializer=tqdm.set_lock, initargs=(tqdm.get_lock(),))
            results = pool.starmap(self.single_process, [(batch, idx) for idx, batch in enumerate(file_chunks)])
            print("DONE.")
        else:
            self.single_process(file_list, 0)
        
        # Remove all the middle files
        shutil.rmtree(APKReader.APKTOOL_FDR, ignore_errors=True)
        shutil.rmtree(APKReader.DEX2JAR_INP, ignore_errors=True)
        if self.clean:
            shutil.rmtree(APKReader.DEX2JAR_OUT, ignore_errors=True)

    def analyse_output(self, output_path):
        """ Analyse DSE output"""
        apk = Path(output_path).stem
        graph_folder = output_path + '/graphs'
        leak = 0
        leak_report_file = output_path + '/taint_dse_summary.txt'
        Path(graph_folder).mkdir(parents=True, exist_ok=True)
        for output in Path(output_path).rglob("*.out"):
            if not output.stem == 'output_' + apk + '.out':
                    if 'StubApp' in output.stem: # Case of stub (packed) app
                        todot(output, apk, graph_folder + '/' + output.stem.replace('output_', '') + '_stub')
                    elif 'JNI' in output.stem or '_so' in output.stem:
                        todot_native(output, apk,  graph_folder + '/' + output.stem.replace('output_', '') + '_native')
                    else:
                        todot(output, apk, graph_folder + '/' + output.stem.replace('output_', '') + '_nostub')
            leak_result = find_leak(output, apk, leak_report_file)
            if leak_result[0]:
                    leak = leak + leak_result[1]
        ("LEAKS from CFG graph: " + str(leak))

if __name__ == "__main__":
    args = sys.argv[1:]
    parser = argparse.ArgumentParser(description='Optional description')
    
    parser.add_argument('path', help='Path to apk file or directory')
    parser.add_argument('analysis', nargs='*', choices=['all', 'dse', 'cha', 'xml'],\
                         default='all', help='Choose analysis action')

    # Optional argument
    parser.add_argument('-n', '--nproc', type=int, default=5,
                        help='Number of paralel processes')
    
    parser.add_argument('-s', '--stamp', help='Name the output folder')
    parser.add_argument('-e', '--exclude', help='Previous history CSV file')
    parser.add_argument('-j', '--keep_jar', action='store_true', help='Keep .jar file after analysis')
    
    args = parser.parse_args()

    main_process = Main()
    main_process.set_options(args.analysis, args.keep_jar)
    main_process.run(args.path, args.nproc, args.stamp)
